name: Build EXE

on: [push]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'  

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller pandas openpyxl
      - name: Build executable
        run: |
          pyinstaller DB_Convolution.spec

      - name: Upload executable
        uses: actions/upload-artifact@v2
        with:
          name: DB_Convolution
          path: dist/
